wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.11
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696504935.630239
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 100
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 100
      3:
      - 23
      4: 3.11.5
      5: 0.15.11
      6: 4.32.1
      8:
      - 5
      13: linux-x86_64
output_dir:
  desc: null
  value: /home/donaldo9603/workspace/BEM/checkpoint/checkpoint-33966
train_dir:
  desc: null
  value: /home/donaldo9603/workspace/numeric/data/ours/numeric_integ_train_add_neg.jsonl
validation_dir:
  desc: null
  value: /home/donaldo9603/workspace/numeric/data/ours/numeric_integ_dev.jsonl
batch_size:
  desc: null
  value: 64
model_name:
  desc: null
  value: microsoft/deberta-v3-base
epoch:
  desc: null
  value: 50
